### ISSUE TITLE
Improved support for mastodon URL recognition in URL field when hash (#) character is used.

### ISSUE THREAD

**Issue by agturcz** [pruvisto/debirdify#15]
As I am using a private mastodon server I wanted to hint people what the URL in my twitter bio is. So, the only way to add some explanation was to expand the URL by # and some text. In case of link detection please ignore the # and reminder part, then check if link is valid fediverse entity.

For reproduction - my twitter handle is @agturcz.

**Comment by agturcz** [comment]
Another twitter handle when link has not been recognized is @brand_the_dwarf - I believe it might be the same issue.

**Comment by pruvisto** [comment]
Fixed as of ab21181d10860ae5d94794cb6a03d5048a12698e.
