### ISSUE TITLE
Feature request: also check lists

### ISSUE THREAD

**Issue by confluence** [pruvisto/debirdify#2]
Would it be possible to fetch additional accounts from a user's saved lists? I use Tweetdeck, and read a large number of accounts by adding them to lists and displaying them in separate columns, without actually following them (because I don't want to clutter up my main feed). It would be helpful if these accounts could be added to the search.

**Comment by pruvisto** [comment]
Fedifinder already does it by now. I never used lists myself so I don't know anything about them, but it should definitely be possible and probably not too much work. I'll look into it, but I might not be able to before next weekend.

**Comment by pruvisto** [comment]
Now implemented as of 394b99533996cbeb3d15f313b8fc550714d4e065.

**Comment by confluence** [comment]
Thank you! I will check it out.
