### ISSUE TITLE
Error authorizing Twitter app - no request token

### ISSUE THREAD

**Issue by ToadKing** [pruvisto/debirdify#22]
I get this error when trying to authorize the app for my Twitter account:

>There is no request token for this page. That's the special key we need from applications asking to use your Twitter account. Please go back to the site or application that sent you here and try again; it was probably just a mistake.

**Comment by pruvisto** [comment]
This is probably a problem with one of your browser extensions, e.g. an ad blocker or some privacy-related extension.

**Comment by ToadKing** [comment]
That was it, launched my browser in safe mode and it worked.
