### ISSUE TITLE
Make different sections for different instances collapsible

### ISSUE THREAD

**Issue by cooljeanius** [pruvisto/debirdify#23]
So, the people I follow are spread out between a bunch of different instances:
<img width="1792" alt="Screen Shot 2022-11-12 at 20 34 17" src="https://user-images.githubusercontent.com/1388660/201501341-c5877129-8647-4e57-8b60-53103eadad5b.png">
This makes scrolling through all the different lists of instances take a really long time. What I'm looking for is like a little triangle that I could click in each of the instance section headers to collapse that list so that I can skip scrolling past it once I'm done with it. By "instance section headers" I mean the parts like this:
<img width="985" alt="Screen Shot 2022-11-12 at 20 34 43" src="https://user-images.githubusercontent.com/1388660/201501395-5cbaa08e-27ac-410d-891e-60793ea8a466.png">

**Comment by cooljeanius** [comment]
oh wait maybe this is a dup of #7 perhaps?

**Comment by pruvisto** [comment]
No, it's not. That's something different.

In principle this is reasonable, but I'd have to figure out how to do that in CSS. The last time I tried to do this I couldn't get it to work and gave up.

If you happen to know how to make something like this, I'd be happy to implement it (or accept a pull request).

**Comment by cooljeanius** [comment]
GCC recently did something similar with its docs using a `<details>` tag: https://gcc.gnu.org/pipermail/gcc-patches/2022-November/605548.html 
Documentation: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details

**Comment by cooljeanius** [comment]
actually, since debirdify seems to be dead now, never mind, I'll just close this...
