### ISSUE TITLE
FYI: Twitter is modifying Mastodon urls in profiles

### ISSUE THREAD

**Issue by dpreuss321** [pruvisto/debirdify#28]
This is an FYI, something I thought you'd want to know. Feel free to just close it after you see it.

Every time I edit my profile on Twitter, it gets saved, but also  *modified* (not what I submitted).

A random character is added to the end of my Mastodon url in my profile. So
Mstdn.ca/@deborahh
becomes
Mstdn.ca/@deborahhw or @deborahhu

I assume it is so apps like debirdify will find invalid IDs. 🤔 now, how could that happen?

PS: I moved my url to the Location field, and it was not modified. Solved, for me.

**Comment by pruvisto** [comment]
That's odd, I've not heard of this issue before. I doubt Twitter is intentionally sabotaging Debirdify.

**Comment by dpreuss321** [comment]
happened three times in a row, yesterday. Today I cannot reproduce. Closing.

**Comment by dpreuss321** [comment]
Aha. I found the issue: it is an HTML render error on my mobile. Spotted the same error in another twitter account profile. But when I looked at mine and theirs in the browser, it looks fine. Phew. Closing issue.
