### ISSUE TITLE
Allow to upload lists

### ISSUE THREAD

**Issue by nemobis** [pruvisto/debirdify#5]
It's great that we can search within lists https://github.com/pruvisto/debirdify/issues/2 but sometimes I have a list of handles I'm interested in for various reasons (someone else's Twitter list I follow, other random lists, [Wikidata items](https://query.wikidata.org/#%23%20People%20on%20Twitter%0ASELECT%20DISTINCT%20%3Fitem%20%3Fhandle%0A%7B%0A%20%20%3Fitem%20wdt%3AP31%20wd%3AQ5.%0A%20%20%3Fitem%20p%3AP2002%20%3FhandleStatement.%0A%20%20%3FhandleStatement%20ps%3AP2002%20%3Fhandle.%0A%20%20%23%20But%20not%20those%20which%20ended%20already%0A%20%20MINUS%20%7B%20%3FhandleStatement%20pq%3AP582%20%3Fendtime%20%7D%20.%0A%20%20%3Fitem%20wdt%3AP8687%20%3Ffollowers.%0A%7D%0AORDER%20BY%20DESC%28%3Ffollowers%29%0ALIMIT%201000) or other). It's tedious to move these to my own lists, so it would be great to be able to upload a CSV file or simple txt with a list of handles to check.

**Comment by pruvisto** [comment]
Sounds reasonable. I'll put it on my to-do list.

**Comment by pruvisto** [comment]
Now implemented and live as of 0227f54308536b6a77c58b1115997f8b6fc617c7.

**Comment by nemobis** [comment]
It works and it's super fast, I already made [extremely important discoveries](https://www.wikidata.org/w/index.php?title=Q151892&diff=prev&oldid=1766255086).

According to https://help.twitter.com/en/managing-your-account/twitter-username-rules the regex should be something like `^([A-Za-z0-9_]{1,15})$`. It might also be wiser to skip non-matching usernames, otherwise you can get suggestions (or error messages) completely unrelated to the usernames uploaded.

**Comment by pruvisto** [comment]
You're right – a silly oversight on my end. Fixed now.

**Comment by pruvisto** [comment]
Invalid usernames are also completely skipped now – the original intention was that something like a CSV file with Twitter handles in the first column should also be accepted, but I think that just unnecessarily complicates the matter.
